### ISSUE TITLE
Create another test that starts both a block producer and a relay node

### ISSUE THREAD

**Issue by aciceri** [mlabs-haskell/spo-anywhere#26]
Starting from [this test](https://github.com/mlabs-haskell/spo-anywhere/blob/main/tests/block-producer.nix) create another one that starts also a relay node.

For now I would say to do this on the same NixOS host. My idea is adding a boolean option to the existing block producer module that when enabled (probably by default it should be `true`) instead of just creating a systemd service for the block producer it also creates a relay node. Then it makes the relay node able to access the block producer node but blocks it from the external connections.

**Comment by zmrocze** [comment]
little trouble is that both nodes boil down to `services.cardano-node` so need to sth a bit cleverer to run both nodes on one machine

**Comment by zmrocze** [comment]
just quickly what i can now think of is:

I wouldn't care to run both nodes on single host, because 1) that's not a real usecase as the whole point of having two nodes was to split block producer from network access completely 2) to just implement it for tests is a waste of time because by the design of `cardano-node` module you'd probably have to use nixos-containers at which point you're doing something similar to running two machines in tests, so lets just run 2 machines.
